# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\USUARIO\Desktop\compilador\compilador_lenguajes\views\designs\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.fileContent = QtWidgets.QTextEdit(self.centralwidget)
        self.fileContent.setEnabled(True)
        self.fileContent.setObjectName("fileContent")
        self.gridLayout.addWidget(self.fileContent, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 4, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.fileName = QtWidgets.QLineEdit(self.centralwidget)
        self.fileName.setEnabled(False)
        self.fileName.setObjectName("fileName")
        self.gridLayout.addWidget(self.fileName, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 4, 1)
        self.fileComponents = QtWidgets.QTextEdit(self.centralwidget)
        self.fileComponents.setEnabled(True)
        self.fileComponents.setMinimumSize(QtCore.QSize(0, 0))
        self.fileComponents.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fileComponents.setObjectName("fileComponents")
        self.gridLayout.addWidget(self.fileComponents, 4, 2, 1, 1)
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        self.openFile.setObjectName("openFile")
        self.gridLayout.addWidget(self.openFile, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 2)
        self.fileValues = QtWidgets.QTextEdit(self.centralwidget)
        self.fileValues.setEnabled(True)
        self.fileValues.setMinimumSize(QtCore.QSize(0, 0))
        self.fileValues.setMaximumSize(QtCore.QSize(16777215, 255))
        self.fileValues.setObjectName("fileValues")
        self.gridLayout.addWidget(self.fileValues, 7, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 8, 1, 1, 2)
        self.label_inter = QtWidgets.QTextEdit(self.centralwidget)
        self.label_inter.setObjectName("label_inter")
        self.gridLayout.addWidget(self.label_inter, 7, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Compilador"))
        self.label.setText(_translate("MainWindow", "Código"))
        self.openFile.setText(_translate("MainWindow", "Abrir Archivo"))
        self.label_3.setText(_translate("MainWindow", "Resultado"))
        self.label_2.setText(_translate("MainWindow", "Lista de Tokens"))
        self.label_4.setText(_translate("MainWindow", "Código intermedio"))
